config/routes.rb
Vs::Application.routes.draw do
  resources :searches

  resources :videos do
    member do
      post :add_comment
    end     
    new do
       post :upload
       get  :save_video
     end
  end

  get "authentications/google"
  match 'auth/google_oauth2/callback', :to => 'authentications#create', via: :get
  
  match 'upload-button', :to => 'videos#upload_button', via: [:get, :post], :as => :upload_button 
  match 'search-button', :to => 'videos#search_button', via: [:get, :post], :as => :search_button


  resources :videos, only: [:index, :new, :create]
  root to: 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	require 'open-uri'
  require 'json'
  acts_as_commentable
  default_scope { order("created_at DESC") }
  attr_accessor :comment
  
  scope :completes,   where(:is_complete => true)
  scope :incompletes, where(:is_complete => false)
  
  has_attached_file :video

  # has_attached_file :video,
  #               :url => "#{Rails.root}/app/assets/images/:basename.:extension",
  #               :path => "#{Rails.root}/app/assets/images/videos/:id/:style/:basename.:extension"
                
  # validates_attachment_presence :video

  validates_attachment_content_type :video,
    :content_type => ['video/avi','video/3gpp','video/wmv','video/mp4','video/mpeg'],
    :message => "Sorry, right now we do not support the video type uploaded",
    :if => :is_type_of_video?

  
  def is_good?
    id = self.yt_video_id
    # url = "https://gdata.youtube.com/feeds/api/users/default/uploads/#{id}"

    if self.youtube_user_url != nil
      client = YouTubeIt::OAuth2Client.new(client_access_token: self.client_access_token, client_refresh_token: self.client_refresh_token, client_id: ENV["GOOGLE_CLIENT_ID"], client_secret: ENV["GOOGLE_CLIENT_SECRET"], dev_key: ENV["DEVELOPER_KEY"], expires_at: self.expiration)
    else 
      client = YouTubeIt::Client.new(:username => ENV['USERNAME'] , :password => ENV['PASSWORD'] , :dev_key => ENV['DEVELOPER_KEY'])
      # client.video_by(id)
    end
    
  end

  def create_comment(comment)
    begin
      comments.create(:comment => comment)
      Video.yt_session.add_comment(yt_video_id, comment)
    rescue
      false
    end
  end
  
    
  def self.yt_session
    @yt_session ||= YouTubeIt::Client.new(:username => 'tonytaudesign' , :password => 'getwithitx5zx5' , :dev_key => "AIzaSyBAbnuOKzE1Pa7A3thvI1GLtpVpHLEnVcs")    
  end

  def self.delete_video(video)
    yt_session.video_delete(video.yt_video_id)
    video.destroy
      rescue
        video.destroy
  end

  def self.update_video(video, params)
    yt_session.video_update(video.yt_video_id, video_options(params))
    video.update_attributes(params)
  end

  def self.token_form(params, nexturl)
    yt_session.upload_token(video_options(params), nexturl)
  end

  def self.delete_incomplete_videos
    self.incompletes.map{|r| r.destroy}
  end

  private
    def self.video_options(params)
      opts = {:title => params[:title],
             :description => params[:description],
             :category => "People",
             :keywords => ["test"]}
      params[:is_unpublished] == "1" ? opts.merge(:private => "true") : opts
    end

    def is_type_of_video?
      video.content_type =~ %r(video)
    end

    

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:edit, :update, :destroy]
  

  # GET /videos
  # GET /videos.json
  def index
    @search = Search.new
    if params[:page].present?
     page = params[:page]
    else
      page = 1
    end
     @video = Video.new 
     @videos = Video.all.where('created_at <= ?' , 1.hours.ago.to_datetime)
     @update = update_message session[:update]
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
    respond_to do |format|               
      format.js
    end   
  end

  def search
    @video = Video.new
    @search = Search.new
    if params[:page].present?
      page = params[:page]
    else
      page = 1
    end
    search = Search.find(params[:id])
    @videos = search.videos.where('created_at > ?' , 1.hours.ago).page(page).per_page(5)
  end

  # GET /videos/new
  def new
    
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    begin
      video = Video.create({title: params[:title], age: params[:age], sex: params[:sex], location: params[:location], keywords: params[:keywords], video: params[:video]})
      url = video.aws_url = video.video.url
      client = YouTubeIt::Client.new(:username => ENV['USERNAME'] , :password => ENV['PASSWORD'] , :dev_key => ENV['DEVELOPER_KEY'])
      youtube_video = client.video_upload(url, title: video.title)
      youtube_url = video.youtube_url = youtube_video.media_content[0].url
      if youtube_url[/youtu\.be\/([^\?]*)/]
        video.yt_video_id = $1
      else
        # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
        youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
        video.yt_video_id = $5
      end
      video.thumbnail = youtube_video.thumbnails[1].url
      video.save
      session[:video] = nil
      flash[:notice]  = "Video uploaded successfully"
     

      render "videos/index"
  
    rescue Exception => e
      session[:update] = "upload_error"
      redirect_to root_path
    end
    # omni_request =  session[:omniauth]
    # token = omni_request["credentials"].token
    # refresh_token = omni_request["credentials"].refresh_token
    # expiration = omni_request["credentials"].expires_at
    # # client = YouTubeIt::OAuth2Client.new(client_access_token: token, client_refresh_token: refresh_token, client_id: ENV["GOOGLE_CLIENT_ID"], client_secret: ENV["GOOGLE_CLIENT_SECRET"], dev_key: ENV["DEVELOPER_KEY"], expires_at: expiration)
    # client = YouTubeIt::Client.new(:username => ENV['DEVELOPER_KEY'] , :password => ENV['DEVELOPER_KEY'] , :dev_key => ENV['DEVELOPER_KEY'])
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' } 
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  def upload
    # client = developer_key
    unless params[:title].present?
      @no_title = true
    else
      @video = Video.create({title: params[:title], age: params[:age].to_i, sex: params[:sex], location: params[:location], keywords: params[:keywords]})
        if @video
        @upload_info = Video.token_form(params, save_video_new_video_url(:video_id => @video.id))
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def save_video
    @video = Video.find(params[:video_id])
    if params[:status].to_i == 200
      client = YouTubeIt::Client.new(:username => "tonytaudesign" , :password => "getwithitx5zx5" , :dev_key => "AIzaSyBAbnuOKzE1Pa7A3thvI1GLtpVpHLEnVcs")
      y_video = client.video_by(params[:id])
      y_video_url = y_video.media_content[0].url
      @video.update_attributes(:yt_video_id => params[:id].to_s, :is_complete => true, :youtube_url => y_video_url  )
      Video.delete_incomplete_videos
      notice = "Video successfully uploaded"
    else
      notice = "Video did not successfully upload"
      Video.delete_video(@video)
    end
    redirect_to videos_path, :notice => notice
  end

  def upload_button
    @video = Video.new
    respond_to do |format|
      format.js
    end
  end

  def search_button
    @search = Search.new
    respond_to do |format|
      format.js
    end
  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:link, :title, :author, :duration, :likes, :dislikes, :age, :sex, :location, :page, :video, :file)
    end


end

app/helpers/videos_helper.rb
module VideosHelper

	def youtube_embed(youtube_url)
	  if youtube_url[/youtu\.be\/([^\?]*)/]
	    youtube_id = $1
	  else
	    # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
	    youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
	    youtube_id = $5
	  end

  	%Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
	end
	
end

app/views/videos/_search.html.erb
<p>Search for a video.</p>

<%= form_for @search do %>
       Age:<br/>
         <%= number_field_tag :age, 24 %> </br>
       Sex:<br/>
       <%= select_tag(:sex, options_for_select([['Male', "Male"], ['Female', "Female"]], selected: :sex )) %> </br>
			 Location:<br/>
			   <%= text_field_tag :location %></br>
       Keywords:<br/>
       <%= text_field_tag :keywords %></br><br/>
    <%= submit_tag "Search", class:"button upload-small" %>
 <% end %>   

app/views/videos/_show.html.erb
	</br>
	<div class="view-all">
	  <%= link_to "View All Videos", root_path %>
	</div>
	<% if video.youtube_url.present? %>
		<div class="video-container">
	    <%= youtube_embed(video.youtube_url).html_safe %>
		</div>
	<% end %>

app/views/videos/_upload.html.erb
<p>Upload a video.</p>

<%= form_for @video, :html => {:multipart => true} do %>

			Title: (required)</br>
				 <%= text_field_tag :title %></br>
			Age:</br>
        <%= number_field_tag :age, 24 %>  </br>
       Sex:</br>
       <%= select_tag(:sex, options_for_select([['Male', "Male"], ['Female', "Female"]], selected: :sex )) %> </br>
			 Location:</br>
			   <%= text_field_tag :location %></br>
       Keywords: (separate by comma)</br>
         <%= text_field_tag :keywords %></br>

</br>

	<%= file_field_tag :video %>

	</br></br>
	<%= submit_tag "Upload Video", class: "button upload-small"%>
<% end %>

app/views/videos/_video.html.erb
<% if video.thumbnail.present? %>
	<div class="box col3 center">
	  <div class="video responsive-video">
	 	  <%= link_to image_tag(video.thumbnail), video_path(video), remote: true %>
	  	<div class="details">
	  	 Title: --  Age: -- Sex: -- Location: --
	  	</div>
		</div>
	</div>
<% end %>

app/views/videos/_video_show.html.erb
<% if video.thumbnail.present? %>
	<div class="box col3 center">
	  <div class="video responsive-video">
	 	  <%= link_to image_tag(video.thumbnail), video_path(video), remote: true %>
	  	<div class="details">
	  	 Title: --  Age: -- Sex: -- Location: --
	  	</div>
		</div>
	</div>
<% end %>

app/views/videos/index.html.erb
<%= render @videos %>
<%#= will_paginate @videos %>

app/views/videos/index.js.erb
$('#videos').append('<%= j render(@videos) %>');
<% if @videos.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@videos) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/videos/save_video.js.erb
$('.upload-form').html("<%= escape_javascript render(@status) %>");

app/views/videos/search.html.erb
<div class="video item">
	<% if @video.youtube_url.present? %>
    <%= youtube_embed(@video.youtube_url).html_safe %>
  <% end %>
  <div class="details">
  	<!-- -->
  </div>
</div>

app/views/videos/search_button.js.erb
$('.upload-form').html('<%= escape_javascript render(:partial => "videos/search", :locals => { :search => @search }) %>');

app/views/videos/show.html.erb
<h1>Search Results</h1>
<div id="container" class="js-masonry" data-masonry-options='{ "columnWidth": 300, "itemSelector": ".item" }'><!--needed for masonry-->
<%#= render @videos %>
<%= will_paginate @videos %>
</div>

app/views/videos/show.js.erb
$('#videos').html('<%= escape_javascript render(:partial => "videos/show", :locals => { :video => @video }) %>');

app/views/videos/upload.js.erb
<% if @no_title %>
  $('.upload-alert').html("<p>Title is Required to upload this video</p>");
<% else %>
  $('.upload-form').html('<%= escape_javascript render(:partial => "videos/upload_two", :locals => { :upload_info => @upload_info }) %>');
<% end %>

app/views/videos/upload_button.js.erb
$('.upload-form').html('<%= escape_javascript render(:partial => "videos/upload_one", :locals => { :video => @video }) %>');